module.exports = {
    'EN': {
        translation: {
            EPISODES : [
            [],
            //Season 1
            [
                'Sorry, I could not find the episode you are looking for.',
                'The Pilot',
                'The One with the Sonogram at the End',
                'The One with the Thumb',
                'The One with George Stephanopoulos',
                'The One with the East German Laundry Detergent',
                'The One with the Butt',
                'The One with the Blackout',
                'The One Where Nana Dies Twice',
                'The One Where Underdog Gets Away',
                'The One with the Monkey',
                'The One With Mrs. Bing',
                'The One With The Dozen Lasagnas',
                'The One With The Boobies',
                'The One with the Candy Hearts',
                'The One with the Stoned Guy',
                'The One with Two Parts: Part 1',
                'The One with Two Parts: Part 2',
                'The One with All the Poker',
                'The One Where the Monkey Gets Away',
                'The One with the Evil Orthodontist',
                'The One with the Fake Monica',
                'The One with the Ick Factor',
                'The One with the Birth',
                'The One Where Rachel Finds Out',                   
            ],
            //Season 2
            [
                'Sorry, I could not find the episode you are looking for.',
                'The One with the Breast Milk',
                'The One with Rosses New Girlfriend',
                'The One Where Heckles Dies',
                'The One with Phoebe\'s Husband',
                'The One with Five Steaks and an Eggplant',
                'The One with the Baby on the Bus',
                'The One Where Ross Finds Out',
                'The One with the List',
                'The One with Phoebe\'s Dad',
                'The One with Russ',
                'The One with the Lesbian Wedding',
                'The One After the Superbowl - Part 1',
                'The One After the Superbowl - Part 2',
                'The One with the Prom Video',
                'The One Where Ross and Rachel ... You Know',
                'The One Where Joey Moves Out',
                'The One Where Eddie Moves In', 
                'The One Where Doctor Ramoray Dies',
                'The One Where Eddie Wont Go',
                'The One Where Old Yeller Dies',
                'The One with the Bullies',
                'The One with the Two Parties',                     
                'The One with the Chicken Pox',
                'The One with Barry and Mindy\'s Wedding'
            ],
            //Season 3
            [
                'Sorry, I could not find the episode you are looking for.',
                'The One With The Princess Leia Fantasy',
                'The One Where No One\'s Ready',
                'The One With The Jam',
                'The One With The Metaphorical Tunnel',
                'The One With Frank, Jr',
                'The One With The Flashback',
                'The One With The Racecar Bed',
                'The One With The Giant Poking Device',
                'The One With The Football',
                'The One Where Rachel Quits',
                'The One Where Chandler Can\'t Remember Which Sister',
                'The One With All The Jealousy',
                'The One Where Monica and Richard Are Just Friends',
                'The One With Phoebe\'s Ex-Partner',
                'The One Where Ross And Rachel Take A Break',
                'The One The Morning After',
                'The One Without The Ski Trip',
                'The One With The Hypnosis Tape',
                'The One With The Tiny T-Shirt',
                'The One With The Dollhouse',
                'The One With a Chick And a Duck',
                'The One With The Screamer',
                'The One With Ross\'s Thing',
                'The One With The Ultimate Fighting Champion',
                'The One At The Beach',
            ],
            //Season 4
            [
                'Sorry, I could not find the episode you are looking for.',
                'The One With The Jellyfish',
                'The One With The Cat',
                'The One With The Cuffs',
                'The One With The Ballroom Dancing',
                'The One With Joey\'s New Girlfriend',
                'The One With The Dirty Girl',
                'The One Where Chandler Crosses The Line',
                'The One With Chandler In A Box',
                'The One Where They\'re Going To PARTY!',
                'The One With The Girl From Poughkeepsie',
                'The One With Phoebe\'s Uterus',
                'The One With The Embryos',
                'The One With Rachel\'s Crush',
                'The One With Joey\'s Dirty Day',
                'The One With All The Rugby',
                'The One With The Fake Party',
                'The One With The Free Porn',
                'The One With Rachel\'s New Dress',
                'The One With All The Haste',
                'The One With All The Wedding Dresses',
                'The One With The Invitation',
                'The One With The Worst Best Man Ever',
                'The One With Ross\'s Wedding, Part 1',
                'The One With Ross\'s Wedding, Part 2',
            ],
            //Season 5
            [
                'Sorry, I could not find the episode you are looking for.',
                'The One After Ross Says Rachel',
                'The One With All The Kissing',
                'The One With The Triplets',
                'The One Where Phoebe Hates PBS',
                'The One With The Kips',
                'The One With The Yeti',
                'The One Where Ross Moves In',
                'The One With All The Thanksgivings',
                'The One With Ross\'s Sandwich',
                'The One With The Inappropriate Sister',
                'The One With All The Resolutions',
                'The One With Chandler\'s Work Laugh',
                'The One With Joey\'s Bag',
                'The One Where Everybody Finds Out',
                'The One With The Girl Who Hits Joey',
                'The One With The Cop',
                'The One With Rachel\'s Inadvertent Kiss',
                'The One Where Rachel Smokes',
                'The One Where Ross Can\'t Flirt',
                'The One With The Ride-Along',
                'The One With The Ball',
                'The One With Joey\'s Big Break',
                'The One In Vegas, Part 1',
                'The One In Vegas, Part 2',
    
            ],
            //Season 6
            [
                'Sorry, I could not find the episode you are looking for.',
                'The One After Vegas',
                'The One Where Ross Hugs Rachel',
                'The One With Ross\'s Denial',
                'The One Where Joey Loses His Insurance',
                'The One With Joey\'s Porsche',
                'The One On The Last Night',
                'The One Where Phoebe Runs',
                'The One With Ross\'s Teeth',
                'The One Where Ross Got High',
                'The One With The Routine',
                'The One With The Apothecary Table',
                'The One With The Joke',
                'The One With Rachel\'s Sister',
                'The One Where Chandler Can\'t Cry',
                'The One That Could Have Been, Part 1',
                'The One That Could Have Been, Part 2',
                'The One With Unagi',
                'The One Where Ross Dates a Student',
                'The One With Joey\'s Fridge',
                'The One With Mac and CHEESE',
                'The One Where Ross Meets Elizabeth\'s Dad',
                'The One Where Paul\'s The Man',
                'The One With The Ring',
                'The One With The Proposal, Part 1',
                'The One With The Proposal, Part 2',
            ],
            //Season 7
            [
                'Sorry, I could not find the episode you are looking for.',
                'The One With Monica\'s Thunder',
                'The One With Rachel\'s Book',
                'The One With Phoebe\'s Cookies',
                'The One With Rachel\'s Assistant',
                'The One With The Engagement Picture',
                'The One With The Nap Partners',
                'The One With Ross\'s Library Book',
                'The One Where Chandler Doesn\'t Like Dogs',
                'The One With All The Candy',
                'The One With the Holiday Armadillo',
                'The One With All The Cheesecakes',
                'The One Where They\'re Up All Night',
                'The One Where Rosita Dies',
                'The One Where They All Turn Thirty',
                'The One With Joey\'s New Brain',
                'The One With The Truth About London',
                'The One With The Cheap Wedding Dress',
                'The One With Joey\'s Award',
                'The One With Ross and Monica\'s Cousin',
                'The One With Rachel\'s Big Kiss',
                'The One With The Vows',
                'The One With Chandler\'s Dad',
                'The One With Monica and Chandler\'s Wedding, Part 1',
                'The One With Monica and Chandler\'s Wedding, Part 2',
                
            ],
            //Season 8
            [
                'Sorry, I could not find the episode you are looking for.',
                'The One After "I Do"',
                'The One With The Red Sweater',
                'The One Where Rachel Tells',
                'The One With The Video Tape',
                'The One With Rachel\'s Date',
                'The One With The Halloween Party',
                'The One With The Stain',
                'The One With The Stripper',
                'The One With The Rumor',
                'The One With Monica\'s Boots',
                'The One With Ross\' Step Forward',
                'The One Where Joey Dates Rachel',
                'The One Where Chandler Takes a Bath',
                'The One With The Secret Closet',
                'The One With The Birthing Video',
                'The One Where Joey Tells Rachel',
                'The One With The Tea Leaves',
                'The One In Massapequa',
                'The One With Joey\'s Interview',
                'The One With The Baby Shower',
                'The One With The Cooking Class',
                'The One Where Rachel is Late',
                'The One Where Rachel Has a Baby, Part 1',
                'The One Where Rachel Has a Baby, Part 2',

            ],
            //Season 9
            [
                'Sorry, I could not find the episode you are looking for.',
                'The One Where No One Proposes',
                'The One Where Emma Cries',
                'The One With the Pediatrician',
                'The One With the Sharks',
                'The One With Phoebe\'s Birthday Dinner',
                'The One With the Male Nanny',
                'The One With Ross\'s Inappropriate Song',
                'The One With Rachel\'s Other Sister',
                'The One With Rachel\'s Phone Number',
                'The One With Christmas in Tulsa',
                'The One Where Rachel Goes Back To Work',
                'The One With Phoebe\'s Rats',
                'The One Where Monica Sings',
                'The One With The Blind Dates',
                'The One With The Mugging',
                'The One With The Boob Job',
                'The One With The Memorial Service',
                'The One With The Lottery',
                'The One With Rachel\'s Dream',
                'The One With The Soap Opera Party',
                'The One With The Fertility Test',
                'The One With The Donor',
                'The One In Barbados, Part 1',
                'The One In Barbados, Part 2',
            ],
            //Season 10
            [
                'Sorry, I could not find the episode you are looking for.',
                'The One After Joey and Rachel Kiss',
                'The One Where Ross is Fine',
                'The One With Ross\'s Tan',
                'The One With the Cake',
                'The One Where Rachel\'s Sister Baby-sits',
                'The One With Ross\'s Grant',
                'The One With the Home Study',
                'The One With the Late Thanksgiving',
                'The One With The Birth Mother',
                'The One Where Chandler Gets Caught',
                'The One Where The Stripper Cries',
                'The One With Phoebe\'s Wedding',
                'The One Where Joey Speaks French',
                'The One With Princess Consuela',
                'The One Where Estelle Dies',
                'The One With Rachel\'s Going Away Party',
                'The Last One, Part 1',
                'The Last One, Part 2',
            ],
            ],
            SKILL_NAME: 'FRIENDS Bot',
            WELCOME_MESSAGE: 'Hi, I can tell you the name of any episode of the popular TV series FRIENDS if you give me a season and episode number.',
            WELCOME_REPROMPT: 'Give me a season number and an episode number',
            HELP_MESSAGE: 'I can tell you the name of any episode of the popular TV series FRIENDS if you give me a season and episode number.',
            HELP_REPROMPT: 'Give me a season number and an episode number',
            STOP_MESSAGE: 'Okay!',
        },
    }
};